create sequence movie_details_sequence start 1;

CREATE TABLE MOVIE_DETAILS
(
    movie_details_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movie_id int not null,
    movie_description varchar(255) not null,
    movie_genre varchar(255) not null
);