create sequence movies_reviews_sequence start 1;

  CREATE TABLE MOVIES_REVIEWS
  (
  review_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  movie_details_id int not null,
  user_id int not null,
  create_dt DATE,
  review_content varchar(20000) not null
  );