create sequence cinema_sequence start 1;

CREATE TABLE CINEMA
(
    cinema_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cinema_company varchar(255) not null,
    cinema_location varchar(255) not null,
    movie_Id int not null,
    cinema_timeSlot varchar(255) not null
);