create sequence cinema_seat_sequence start 1;

CREATE TABLE CINEMA_SEAT
(
    cinema_seat_pk BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seat_Id int not null,
    cinema_Id int not null,
    availability boolean not null
);